version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: argus
      POSTGRES_USER: argus
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres
    volumes:
      - ./db/changelog:/liquibase/changelog
    command: update
    environment:
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/argus
      LIQUIBASE_USERNAME: argus
      LIQUIBASE_PASSWORD: ${DB_PASSWORD}
      LIQUIBASE_CHANGELOG_FILE: /liquibase/changelog/db.changelog-master.yaml

volumes:
  postgres_data: